name: PR Review with Bedrock
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  review:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
      - name: Run Pr-Agent with AWS Bedrock
        uses: Codium-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTION.AUTO_IMPROVE: true

          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: "日本語で説明してください。"
          PR_REVIEWER.EXTRA_INSTRUCTIONS: >-
            日本語で回答してください。
            以下の原則に従ってコメントしてください。
            console.log()等のデバッグコードを残してはいけない。
            文字列にはシングルクォートを使用しなければならない。
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: >-
            日本語で回答してください。
            以下の原則に従ってコメントしてください。
            console.log()等のデバッグコードを残してはいけない。
          PR_ADD_DOCS.EXTRA_INSTRUCTIONS: "日本語で説明してください。"
          PR_CODE_SUGGESTIONS.COMMITABLE_CODE_SUGGESTIONS: TRUE
          PR_CODE_SUGGESTIONS.NUM_CODE_SUGGESTIONS: 10
          PR_CODE_SUGGESTIONS.NUM_CODE_SUGGESTIONS_PER_CHUNK: 10
